stages:
  - build
  - push

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

.build_template:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build_moodle_plugin_ci:
  extends: .build_template
  parallel:
    matrix:
      - PHP_VERSION: ["8.1", "8.2", "8.3", "8.4"]
  script:
    - docker build --build-arg PHP_VERSION=${PHP_VERSION} -t $DOCKERHUB_REPO:${PHP_VERSION} .
    - docker push $DOCKERHUB_REPO:${PHP_VERSION}
